export const images = {
  cart: require('../assets/images/Cart_icon.png'),
  menu: require('../assets/images/Menu.png'),
  search: require('../assets/images/Search_Icon.png'),
  filter: require('../assets/images/Filter_Icon.png'),
  plants1: require('../assets/images/plants1.png'),
  plants2: require('../assets/images/plants2.png'),
  plants3: require('../assets/images/plants3.png'),
  plus: require('../assets/images/Plus.png'),
  cross: require('../assets/images/Vector.png'),
  drop: require('../assets/images/Drop_Icon.png'),
  sun: require('../assets/images/Sun_Icon.png'),
  temperature: require('../assets/images/Temparatur_Icon.png'),
  up_point: require('../assets/images/up_point.png'),
  left_arrow: require('../assets/images/Arrow.png'),
  heart: require('../assets/images/Heart_Icon.png'),
  minus: require('../assets/images/Minus.png'),
  plus_small: require('../assets/images/plus_small.png'),
  pot: require('../assets/images/pot.png'),
  check: require('../assets/images/Check.png'),
  cartSmall: require('../assets/images/Cart_small.png'),
};
